server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cs?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: root
  web:
    resources:
      static-locations: file:D:/file,classpath:static
mybatis:
  configuration:
    map-underscore-to-camel-case: true
knife4j:
  enable: true
